### ISSUE TITLE
[BUG] ProtonVPN won't initialize

### ISSUE THREAD

**Issue by nixin72** [ProtonVPN/protonvpn-cli-ng#133]
**Describe the bug**
ProtonVPN won't initialize

**To Reproduce**
1. Download github repo
2. `cd` into the repo
3. run `pip3 install -e .`
4. run `sudo protonvpn init`

**Expected behavior**
ProtonVPN to initialize a new profile

**Error Messages/Program Output/Log Messages**
```
Traceback (most recent call last):
  File "/home/<user>/.local/bin/protonvpn", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'protonvpn-cli' distribution was not found and is required by the application
```
No entry in the log file is created.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux KDE 18
 - Python Version: 3.8.1
 - ProtonVPN-CLI Version: 2.2.2

**Additional context**
I have all the dependencies installed through running `sudo pacman -S openvpn dialog python-pip python-setuptools` and I previously tried installing protonvpn through running `sudo pip3 install protonvpn-cli` as suggested in the readme, but was getting [pip related errors](https://github.com/pypa/pip/issues/5599) with that. I don't believe this is related though. Although I would note that issue advises against running `pip` as root.

**Comment by Rafficer** [comment]
You need to run `sudo pip3 install -e .`

**Comment by ILikeToHelp** [comment]
> 
> 
> You need to run `sudo pip3 install -e .`

Can confirm this worked for me. 
Could the documentation be updated? Or at least prefix the command with standard  "#" for sudo instructions?
Thank you.

**Comment by Rafficer** [comment]
It's mean to be done in a virtual environment, where `sudo` wouldn't be able to be used.

This could be made more clear in the documentation, I agree.

**Comment by BlackSonic2** [comment]
I am a proton VPN Plus user. I stopped using proton VPN now. I am not a guru of different programs or software. Proton hasn't been reliable to keep people safe in my opinion. Kicks me off, and Strongswan VPN is always activated. Don't trust Strongswan. Don't trust Proton VPN now either anymore!

Sent from ProtonMail mobile

-------- Original Message --------
