### ISSUE TITLE
[BUG] 'ascii' codec can't encode character inside docker

### ISSUE THREAD

**Issue by Paulpatou** [ProtonVPN/protonvpn-cli-ng#145]
**Describe the bug**
protonvpn sends an encoding error every time I execute a "protonvpn ..." command but the commands still work!

**To Reproduce**
```
FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive


RUN apt-get update && \
    apt-get install -y openvpn dialog python3-pip python3-setuptools  && \
    pip3 install protonvpn-cli
```

**Expected behavior**
Remove unnecessary messages 

**Error Messages/Program Output/Log Messages (~/.pvpn-cli/pvpn-cli.log)**
```
root@5b7648e8df26:/# protonvpn --version
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 24: ordinal not in range(128)
Call stack:
  File "/usr/local/bin/protonvpn", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 84, in cli
    logger.debug("###########################")
Message: '###########################'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 24: ordinal not in range(128)
Call stack:
  File "/usr/local/bin/protonvpn", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 85, in cli
    logger.debug("### NEW PROCESS STARTED ###")
Message: '### NEW PROCESS STARTED ###'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 24: ordinal not in range(128)
Call stack:
  File "/usr/local/bin/protonvpn", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 86, in cli
    logger.debug("###########################")
Message: '###########################'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 24: ordinal not in range(128)
Call stack:
  File "/usr/local/bin/protonvpn", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 87, in cli
    logger.debug(sys.argv)
Message: ['/usr/local/bin/protonvpn', '--version']
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 24: ordinal not in range(128)
Call stack:
  File "/usr/local/bin/protonvpn", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 88, in cli
    logger.debug("USER: {0}".format(USER))
Message: 'USER: root'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 24: ordinal not in range(128)
Call stack:
  File "/usr/local/bin/protonvpn", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 89, in cli
    logger.debug("CONFIG_DIR: {0}".format(CONFIG_DIR))
Message: 'CONFIG_DIR: /root/.pvpn-cli'
Arguments: ()
ProtonVPN-CLI v2.2.2
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 container inside Ubuntu 16.04
 - Python 3.6.9
 - ProtonVPN-CLI v2.2.2

**Additional context**

**Comment by Rafficer** [comment]
Python in the Ubuntu container does that. Not the CLI. This doesn't happen in an arch container for example.

**Comment by Paulpatou** [comment]
Yes it does work on archlinux but I have another problem now. I don't think it's from Protonvpn, but here's the stackoverflow link.
https://stackoverflow.com/questions/60972874/valueerror-invalid-width-0-must-be-0/60973493#60973493

**Comment by Rafficer** [comment]
Set it up on your machine, then copy the pvpn-cli folder over to the container instead of setting up the cli inside the container with an expect script.

**Comment by Paulpatou** [comment]
Okay, okay. Interesting. I'll try that. This is the hidden folder in /home/user/.pvpn-cli ?

**Comment by Rafficer** [comment]
Yes.

**Comment by Rafficer** [comment]
Btw, it will likely still not work after that: https://github.com/ProtonVPN/protonvpn-cli-ng/issues/120

**Comment by Paulpatou** [comment]
Indeed I meet the same error but I manage to bypass with this in my ENTRYPOINT 
```
cp /etc/resolv.conf /tmp/resolv.conf
su -c 'umount /etc/resolv.conf'
cp /tmp/resolv.conf /etc/resolv.conf
```

But it's a slightly shaky track and I'd rather not use it because I've got another errors afterwards.
Any ETA on a solution from your side ?

**Comment by Rafficer** [comment]
Next release, whenever that will happen. No ETA, yet, sadly.

**Comment by MCRayRay** [comment]
I have experienced this as well but natively, not on Docker.

I believe the issue to linked to Python using the system's locale for some functions to do with encoding/decoding. I haven't looked into it more than that.

I noticed that when I changed the locale to en_GB.UTF-8 the problem went away.

Before, the locale was set to POSIX.

You should be able to replicate this issue if you change the system locale to POSIX:
`# localectl set-locale LANG=POSIX`

What I suspect, then, is that the Debian Docker container's locale is set to something unexpected.

I hope this helps somewhat.

**Comment by Rafficer** [comment]
Awesome, thank you @MCRayRay!

Adding `ENV LANG=C.UTF-8` as instruction to the Dockerfile fixes this. Alternatively one can also start the container with `-e LANG=C.UTF-8`.

Btw, the same is the case for LXC containers.

Tbh, I don't think that this is something the CLI can ultimately fix so this isn't needed. As this is just a small issue and a very easy mitigate, I think it's fine to leave it at that.

**Comment by andreapx** [comment]
I'm having the almost same problem with LXC on Proxmox.
I've change the locale, but when I try to initialize protonvpn, I get this errors:
`Is this information correct? [Y/n]: y
Writing configuration to disk...
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 24: ordinal not in range(128)
Call stack:
  File "/usr/local/bin/protonvpn", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 96, in cli
    init_cli()
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 241, in init_cli
    init_config_file()
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 174, in init_config_file
    logger.debug("pvpn-cli.cfg initialized")
Message: 'pvpn-cli.cfg initialized'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 24: ordinal not in range(128)
Call stack:
  File "/usr/local/bin/protonvpn", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 73, in main
    cli()
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 96, in cli
    init_cli()
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/cli.py", line 243, in init_cli
    pull_server_data()
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/utils.py", line 83, in pull_server_data
    data = call_api("/vpn/logicals")
  File "/usr/local/lib/python3.6/dist-packages/protonvpn_cli/utils.py", line 36, in call_api
    logger.debug("Initiating API Call: {0}".format(url))
Message: 'Initiating API Call: https://api.protonvpn.ch/vpn/logicals'
Arguments: ()`

**Comment by Rafficer** [comment]
What's the Output of `echo $LANG`?

**Comment by andreapx** [comment]
It's onle `C`

**Comment by Rafficer** [comment]
What's the Output of `locale -a`?

**Comment by andreapx** [comment]
`C
C.UTF-8
POSIX
en_GB.utf8`

**Comment by Rafficer** [comment]
It seems like you didn't follow above instructions. Change the locale to `C.UTF-8` or `en_GB.utf-8`.

**Comment by andreapx** [comment]
I did it with this command:
`localectl set-locale LANG=C.UTF-8`

**Comment by Rafficer** [comment]
Did you relog after that? Maybe even try a reboot.

What's the output of `localectl`?

**Comment by andreapx** [comment]
Ops...it worked after a reboot.
THANKS!
