### ISSUE TITLE
protonvpn status crashing or giving an error

### ISSUE THREAD

**Issue by ploum** [ProtonVPN/protonvpn-cli-ng#5]
the "status" command is not working on Ubuntu 19.04. Either it crashes with the following trace :
 sudo protonvpn s
Traceback (most recent call last):
  File "/usr/local/bin/protonvpn", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/cli.py", line 103, in main
    cli()
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/cli.py", line 160, in cli
    connection.status()
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/connection.py", line 398, in status
    country = get_country_name(country_code)
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/utils.py", line 148, in get_country_name
    with open(cc_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/protonvpn_cli/country_codes.json'

or it returns the following:
 sudo protonvpn status
[!] Could not reach the VPN Server
[!] You may want to reconnect with 'pvpn-cli reconnect'

**Comment by Rafficer** [comment]
The issue is already fixed, you're probably using v0.1.0?

This Version has only been pushed to pypi to secure the name on pypi.

If you perform a manual install it should work fine.

The release on pypi and announcements will still take a bit more time :)
