### ISSUE TITLE
[BUG] Connection Failed - cli.py

### ISSUE THREAD

**Issue by jallm** [ProtonVPN/protonvpn-cli-ng#57]
Hello, 
I tried to connect on my freshly installed raspbian and couldn't use pvpn this time, like I used to do. I've already reinstalled the pvpn-ng...
Every time i try to connect now this message apears:
____________________________________________________________________________________________________
Traceback (most recent call last):
  File "/usr/local/bin/protonvpn", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/cli.py", line 72, in main
    cli()
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/cli.py", line 120, in cli
    connection.dialog()
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/connection.py", line 123, in dialog
    openvpn_connect(server_result, protocol_result)
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/connection.py", line 463, in openvpn_connect
    disconnect(passed=True)
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/connection.py", line 339, in disconnect
    manage_dns("restore")
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/connection.py", line 612, in manage_dns
    oldhash = get_config_value("metadata", "resolvconf_hash")
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/utils.py", line 113, in get_config_value
    return config[group][key]
  File "/usr/lib/python3.7/configparser.py", line 1251, in __getitem__
    raise KeyError(key)
KeyError: 'resolvconf_hash'
_____________________________________________________________________________________________________

Desktop:
 - OS:  Raspbian Buster 
 - Python Version: 3.7.3
 - ProtonVPN-CLI Version: 2.1.2

**Comment by Rafficer** [comment]
Are you by any chance able to reproduce this consistently? If so, please share with me how!

**Comment by jallm** [comment]
Hello, Rafficer!
It happened instantly every time I tried to connect any server or tried the Purge option of configuration. 
Your advice fixed the error, thanks!
