### ISSUE TITLE
[Bug] - Connect command fails

### ISSUE THREAD

**Issue by Dvlnst** [ProtonVPN/protonvpn-cli-ng#6]
Hi,

Command **sudo protonvpn c** fails:
```

Traceback (most recent call last):
  File "/usr/local/bin/protonvpn", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/cli.py", line 103, in main
    cli()
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/cli.py", line 150, in cli
    connection.dialog()
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/connection.py", line 65, in dialog
    country = get_country_name(server["ExitCountry"])
  File "/usr/local/lib/python3.7/dist-packages/protonvpn_cli/utils.py", line 148, in get_country_name
    with open(cc_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/protonvpn_cli/country_codes.json'
```

Testing in Debian 10.

Kind Regards.

**Comment by Rafficer** [comment]
Same as #5 and fixed already.
